### ISSUE TITLE
Provide example screenshot in readme

### ISSUE THREAD

**Issue by pronoiac** [lukehorvat/screenshot-tweet#1]
Wishlist: show how the screenshots look.

**Comment by pronoiac** [comment]
I made an example screenshot from [this tweet:](https://twitter.com/film_girl/status/938562300230774785) 
![example](https://user-images.githubusercontent.com/171153/33812003-0c247e02-ddce-11e7-8ba9-6d8d16cfbe00.jpg)

**Comment by johnpaulRod** [comment]
what about the file path .... the script ignore the '/' and sets the whole path as the file name...
